# Generated by Django 5.2.8 on 2025-11-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookissue',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bookissue',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('active', 'Active'), ('returned', 'Returned')], default='active', max_length=10),
        ),
    ]
