# Generated by Django 5.2.8 on 2025-11-11 16:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_bookissue_notes_bookissue_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('issue_approved', 'Issue Approved'), ('issue_rejected', 'Issue Rejected'), ('due_soon', 'Due Soon'), ('overdue', 'Overdue'), ('returned', 'Book Returned'), ('fine_added', 'Fine Added'), ('fine_paid', 'Fine Paid'), ('system', 'System Notification')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='books_notif_user_id_184488_idx'), models.Index(fields=['-created_at'], name='books_notif_created_d870aa_idx')],
            },
        ),
    ]
